CREATE TABLE PREPODAVATEL (
    FIO        VARCHAR2(100),
    DISCIPLINE VARCHAR2(100),
    TELEPHONE  NUMBER(11),
    POCHTA     VARCHAR2(50)
);

CREATE TABLE PAIR (
    AUDITORY                  NUMBER(3),
    DISCIPLINE                VARCHAR2(100),
    VREMYA_I_DEN_OF_NEDELYA   DATE,
    TYPE_SEMINAR1_OR_LECTION2 NUMBER(1)
);

CREATE TABLE LOCATION_ (
    AUDITORY NUMBER(3),
    CORPSE   VARCHAR2(100),
    ADRESS   VARCHAR2(100)
);

ALTER TABLE PREPODAVATEL ADD (
    CONSTRAINT OGRANICHENIE UNIQUE ( POCHTA )
);

ALTER TABLE LOCATION_ MODIFY
    CORPSE NOT NULL;

ALTER TABLE LOCATION_ MODIFY
    ADRESS NOT NULL;

ALTER TABLE PREPODAVATEL ADD (
    CONSTRAINT NOMER CHECK ( TELEPHONE BETWEEN 79999999999 AND 90000000000 )
);

ALTER TABLE PAIR ADD (
    CONSTRAINT TYPO CHECK ( TYPE_SEMINAR1_OR_LECTION2 BETWEEN 0 AND 3 )
);

ALTER TABLE PREPODAVATEL ADD (
    CONSTRAINT DISCIPLINE_PK PRIMARY KEY ( DISCIPLINE )
);

ALTER TABLE LOCATION_ ADD (
    CONSTRAINT AUDITORY_PK PRIMARY KEY ( AUDITORY )
);

ALTER TABLE PAIR ADD (
    CONSTRAINT DISCIPLINE_FK FOREIGN KEY ( DISCIPLINE )
        REFERENCES PREPODAVATEL ( DISCIPLINE )
);

ALTER TABLE PAIR ADD (
    CONSTRAINT AUDITORY_FK FOREIGN KEY ( AUDITORY )
        REFERENCES LOCATION_ ( AUDITORY )
);